name: Tag

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string

jobs:

  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0

      - name: Get latest semver tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --abbrev=0 --match 'v[0-9]*.[0-9]*.[0-9]*' 2>/dev/null) || latest_tag=v0.0.0
          echo "tag=$latest_tag" >> "$GITHUB_OUTPUT"

      - name: Bump version
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch

      - name: Push new tag
        run: |
          tag=${{ steps.bump-semver.outputs.new_version }}

          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git tag -a "${tag}" -m ''
          git push origin "${tag}"
